future: true
permalink: pretty
url: http://pmlpml.github.io
name: Pan Sir
author: Sir Pan
qq: yourqq
email: panml@mail.sysu.edu.cn

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: pmlpml
about: "这里是 Your 的个人博客，创建于 20xx 年。"

safe: true
paginate: 20
